version: "3.7"
services: 
  app:
    image: node:12-alpine
    command: sh -c "yarn install && tail -F anything"
    working_dir: /app
    volumes: 
      - ./:/app
  zookeeper:
    image: zookeeper
    ports: 
      - 2181:2181
  kafka:
    image: bitnami/kafka
    ports: 
      - 9092:9092
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    